name: Bug Report
description: Report a bug or unexpected behavior
title: "BUG: "
labels: ["bug"]

body:
  - type: checkboxes
    id: checks
    attributes:
      label: Initial Checks
      options:
        - label: I have searched the existing issues and this bug has not been reported
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Provide a minimal code example or steps to reproduce the issue.
      placeholder: |
        ```ts
        import { Agent } from "@stirrup/stirrup";

        // Your minimal repro here
        const agent = new Agent({
          // ...
        });
        ```
      render: typescript
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details.
      placeholder: |
        - Node.js version:
        - Package manager + version (npm/pnpm/yarn/bun):
        - @stirrup/stirrup version:
        - OS:
    validations:
      required: true
